// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CoSendListDao is the data access object for table co_send_list.
type CoSendListDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns CoSendListColumns // columns contains all the column names of Table for convenient usage.
}

// CoSendListColumns defines and stores column names for table co_send_list.
type CoSendListColumns struct {
	Id           string //
	SendId       string //
	Receive      string //
	Status       string //
	SendServerId string //
}

// coSendListColumns holds the columns for table co_send_list.
var coSendListColumns = CoSendListColumns{
	Id:           "id",
	SendId:       "send_id",
	Receive:      "receive",
	Status:       "status",
	SendServerId: "send_server_id",
}

// NewCoSendListDao creates and returns a new DAO object for table data access.
func NewCoSendListDao(proxy ...dao_interface.IDao) *CoSendListDao {
	var dao *CoSendListDao
	if len(proxy) > 0 {
		dao = &CoSendListDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: coSendListColumns,
		}
		return dao
	}

	return &CoSendListDao{
		group:   "default",
		table:   "co_send_list",
		columns: coSendListColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CoSendListDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CoSendListDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *CoSendListDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *CoSendListDao) Columns() CoSendListColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CoSendListDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *CoSendListDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CoSendListDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
