// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_entity

// SysPersonAudit is the golang structure for table sys_person_audit.
type SysPersonAudit struct {
}
