// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_dao

import (
	"github.com/jack353249002/exam-message-send/sys_model/sys_dao/internal"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
)

type SysUserDetailDao = dao_interface.TIDao[internal.SysUserDetailColumns]

func NewSysUserDetail(dao ...dao_interface.IDao) SysUserDetailDao {
	return (SysUserDetailDao)(internal.NewSysUserDetailDao(dao...))
}

var (
	SysUserDetail = NewSysUserDetail()
)
