// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sys_do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysPersonAudit is the golang structure of table sys_person_audit for DAO operations like Where/Data.
type SysPersonAudit struct {
	g.Meta `orm:"table:sys_person_audit, do:true"`
}
